\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\PassOptionsToPackage{usenames,dvipsnames}{color} % color is loaded by hyperref
\hypersetup{unicode=true,
            pdftitle={Pràctica 2: Neteja i anàlisi de les dades},
            pdfauthor={Mireia Olivella i Gabriel Izquierdo},
            colorlinks=true,
            linkcolor=Maroon,
            citecolor=Blue,
            urlcolor=blue,
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Pràctica 2: Neteja i anàlisi de les dades}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Mireia Olivella i Gabriel Izquierdo}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{4 de maig de 2020}

\renewcommand{\contentsname}{Índex}

\begin{document}
\maketitle

{
\hypersetup{linkcolor=black}
\setcounter{tocdepth}{3}
\tableofcontents
}
\pagebreak

\hypertarget{descripciuxf3-del-dataset}{%
\section{Descripció del dataset}\label{descripciuxf3-del-dataset}}

El conjunt de dades escollit recull informació dels passatgers del
titanic, en el que es pot analitzar la superviència i les
característiques d'aquests. Aquest conjunt de dades s'ha obtingut de la
web de Kaggle. S'hi pot accedir a partir de l'enllaç que es mostra a
continuació:

\url{https://www.kaggle.com/c/titanic}

El conjunt de dades utilitzat està format per 1309 registres amb 12
atributs dividit en 2 fitxers CSV, un de \emph{train} i un de
\emph{test}, ja que aquest conjunt de dades està preparat per ser
utilitzat per tasques de predicció. Els atributs d'aquest conjunt de
dades són els següents:

\begin{itemize}
\tightlist
\item
  \textbf{passengerId}: identificador dels registres del dataset.
\item
  \textbf{survived}: indica si el passatger va sobreviure (0=No, 1=Sí).
\item
  \textbf{pclass}: indica la classe en la que viatjava el passatger
  (1=1a, 2=2a, 3=3a).
\item
  \textbf{name}: nom del passatger.
\item
  \textbf{sex}: gènere del passatger (\emph{female} o \emph{male}).
\item
  \textbf{age}: edat del passatger.
\item
  \textbf{sibsp}: número de germans i cònjugues a bord del Titànic.
\item
  \textbf{parch}: número de pares i fills a bord del Titànic.
\item
  \textbf{ticket}: número del bitllet
\item
  \textbf{fare}: preu de compra del bitllet.
\item
  \textbf{cabin}: número de cabina on viatjava el passatger.
\item
  \textbf{embarked}: port on va embarcar el passatger (C=Cherbourg,
  Q=Queenstown, S=Southampton).
\end{itemize}

Aquest conjunt de dades és important perquè representa les dades d'un
dels naufragis més infames de la història. A més, ens permet abastir
tots els aspectes importants a tenir en compte a l'hora de dur a terme
aquesta pràctica.

La pregunta que intenta respondre és la de quins són els factors que van
afavorir a un passatger sobreviure al naufragi. Si bé hi havia un
element de sort en la supervivència dels passatgers, sembla que alguns
grups de persones tenien més probabilitats de sobreviure que d'altres.

\hypertarget{neteja-de-les-dades}{%
\section{Neteja de les dades}\label{neteja-de-les-dades}}

Abans de començar amb la neteja de les dades, procedim a realitzar les
lectures dels fitxers en format CSV en el que es troben. El procediment
és el de carregar la informació dels tres fitxers i unir-les
posteriorment.

En la secció anterior s'ha parlat de dos fitxers de tipus CSV, i ara se
n'ha parlat de tres. Això es deu a que al fitxer \texttt{test.csv} li
falta un atribut respecte al fitxer \texttt{train.csv}, que és el de
\texttt{Survived}. La informació referent a la supervivència dels
passatgers del fitxer \texttt{test.csv} es troba en un altre fitxer
anomenat \texttt{gender\_submission.csv} que té només dues columnes:
\texttt{PassengerId} i \texttt{Survived}.

El primer que fem és carregar la informació de tots els fitxers CSV.
Després fem un \emph{merge} de les dades de \texttt{test.csv} i
\texttt{gender\_submission.csv} utilitzant la funció \texttt{merge} amb
l'atribut \texttt{PassengerId} com a clau comuna entre les dues taules.
Per acabar s'uneixen totes les dades de \emph{train} i \emph{test} en un
sol \emph{dataframe} utilitzant la funció \texttt{rbind}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Lectura de les dades}
\NormalTok{titanic_train <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"../data/train.csv"}\NormalTok{)}
\NormalTok{titanic_test <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"../data/test.csv"}\NormalTok{)}
\NormalTok{titanic_gender_submission <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"../data/gender_submission.csv"}\NormalTok{)}
\NormalTok{titanic_test <-}\StringTok{ }\KeywordTok{merge}\NormalTok{(titanic_test, titanic_gender_submission, }\DataTypeTok{by=}\StringTok{"PassengerId"}\NormalTok{)}
\NormalTok{titanic_data <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(titanic_train, titanic_test)}
\KeywordTok{head}\NormalTok{(titanic_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   PassengerId Survived Pclass
## 1           1        0      3
## 2           2        1      1
## 3           3        1      3
## 4           4        1      1
## 5           5        0      3
## 6           6        0      3
##                                                  Name    Sex Age SibSp Parch
## 1                             Braund, Mr. Owen Harris   male  22     1     0
## 2 Cumings, Mrs. John Bradley (Florence Briggs Thayer) female  38     1     0
## 3                              Heikkinen, Miss. Laina female  26     0     0
## 4        Futrelle, Mrs. Jacques Heath (Lily May Peel) female  35     1     0
## 5                            Allen, Mr. William Henry   male  35     0     0
## 6                                    Moran, Mr. James   male  NA     0     0
##             Ticket    Fare Cabin Embarked
## 1        A/5 21171  7.2500              S
## 2         PC 17599 71.2833   C85        C
## 3 STON/O2. 3101282  7.9250              S
## 4           113803 53.1000  C123        S
## 5           373450  8.0500              S
## 6           330877  8.4583              Q
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Tipus de dada assignat a cada camp}
\KeywordTok{sapply}\NormalTok{(titanic_data, }\ControlFlowTok{function}\NormalTok{(x) }\KeywordTok{class}\NormalTok{(x))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## PassengerId    Survived      Pclass        Name         Sex         Age 
##   "integer"   "integer"   "integer"    "factor"    "factor"   "numeric" 
##       SibSp       Parch      Ticket        Fare       Cabin    Embarked 
##   "integer"   "integer"    "factor"   "numeric"    "factor"    "factor"
\end{verbatim}

Podem observar que els tipus de dades assignats automàticament per R a
les nostres variables no s'acaben de correspondre amb el domini
d'aquestes. Aquest és el cas de l'atribut \texttt{Survived}. R detecta
que es tracta d'un \emph{integer}, quan en realitat es tracta d'un
\emph{factor}, pel que procedim a assignar-li el tipus que nosaltres
volem.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Canvi del tipus del camp 'Survived'}
\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{Survived <-}\StringTok{ }\KeywordTok{factor}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Survived)}
\end{Highlighting}
\end{Shaded}

\hypertarget{selecciuxf3-de-les-dades-dinteruxe8s}{%
\subsection{Selecció de les dades
d'interès}\label{selecciuxf3-de-les-dades-dinteruxe8s}}

Totes les variables que tenim en el dataset fan referència a
característiques dels passatgers del titanic. Tot i això, podem
precindir de les columnes \emph{PassengerId}, \emph{Name}, \emph{Ticket}
i \emph{Cabin} ja que no aporten informació rellevant de cara a la
pregunta que respon aquest conjunt de dades.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Eliminació de les columes 'PassengerId', 'Name', 'Ticket' i 'Cabin'}
\NormalTok{titanic_data <-}\StringTok{ }\KeywordTok{select}\NormalTok{(titanic_data, }\OperatorTok{-}\KeywordTok{c}\NormalTok{(PassengerId, Name, Ticket, Cabin))}
\KeywordTok{summary}\NormalTok{(titanic_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Survived     Pclass          Sex           Age            SibSp       
##  0:815    Min.   :1.000   female:466   Min.   : 0.17   Min.   :0.0000  
##  1:494    1st Qu.:2.000   male  :843   1st Qu.:21.00   1st Qu.:0.0000  
##           Median :3.000                Median :28.00   Median :0.0000  
##           Mean   :2.295                Mean   :29.88   Mean   :0.4989  
##           3rd Qu.:3.000                3rd Qu.:39.00   3rd Qu.:1.0000  
##           Max.   :3.000                Max.   :80.00   Max.   :8.0000  
##                                        NA's   :263                     
##      Parch            Fare         Embarked
##  Min.   :0.000   Min.   :  0.000    :  2   
##  1st Qu.:0.000   1st Qu.:  7.896   C:270   
##  Median :0.000   Median : 14.454   Q:123   
##  Mean   :0.385   Mean   : 33.295   S:914   
##  3rd Qu.:0.000   3rd Qu.: 31.275           
##  Max.   :9.000   Max.   :512.329           
##                  NA's   :1
\end{verbatim}

\hypertarget{dades-amb-elements-buits-valors-perduts}{%
\subsection{Dades amb elements buits (valors
perduts)}\label{dades-amb-elements-buits-valors-perduts}}

Aquest conjunt de dades conté dades amb elements buits representats de
dues maneres diferents: amb el valor NA (\emph{Not Available}) i amb un
espai en blanc, pel que es procedeix a comprovar quins camps contenen
elements buits i en quina quantitat.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Número de valors perduts per camp}
\KeywordTok{colSums}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(titanic_data))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Survived   Pclass      Sex      Age    SibSp    Parch     Fare Embarked 
##        0        0        0      263        0        0        1        0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{colSums}\NormalTok{(titanic_data }\OperatorTok{==}\StringTok{ ""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Survived   Pclass      Sex      Age    SibSp    Parch     Fare Embarked 
##        0        0        0       NA        0        0       NA        2
\end{verbatim}

Com es pot observar tenim 2 valors en blanc a la variable
\emph{Embarked}, 1 valor NA a \emph{Fare} i 263 valors NA a \emph{Age}.

Primer de tot tractarem els valors en blanc de la variable
\emph{Embarked}. Ens basarem en utilitzar una mesura de tendència
central i, al tractar-se d'una variable categòrica, utilitzarem la
\textbf{moda}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Consulta de la moda de la variable 'Embarked'}
\KeywordTok{mlv}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Embarked, }\DataTypeTok{method =} \StringTok{"mfv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] S
## Levels:  C Q S
\end{verbatim}

Com es pot observar, al ser \emph{S} la moda prenem aquest valor per
omplir als valors buits de la variable.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Imputació dels valors buits de la variable 'Embarked'}
\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{Embarked[titanic_data}\OperatorTok{$}\NormalTok{Embarked }\OperatorTok{==}\StringTok{ ""}\NormalTok{] =}\StringTok{ "S"}
\end{Highlighting}
\end{Shaded}

Per tractar el valor perdut a la variable \emph{Fare} s'utilitzarà la
\textbf{mitjana}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Imputació dels valors buits de la variable 'Fare'}
\NormalTok{titanic_data[}\KeywordTok{is.na}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Fare),]}\OperatorTok{$}\NormalTok{Fare <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Fare, }\DataTypeTok{na.rm =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Per acabar, per tractar els valors perduts de la variable \emph{Age}
s'utilitzarà la \textbf{mitjana}. Per dur a terme la obtenció d'aquesta
mitjana, enlloc d'obtenir la mitjana de l'atribut \emph{Age} sencer,
tindrem en compte el gènere (\emph{Sex}) i la classe en la que viatjava
(\emph{Pclass}). A la gràfica següent es pot observar la relació entre
els atributs \emph{Age} i \emph{Pclass} per dones i per homes.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Visualitzem la relació entre les variables 'Age' i 'Pclass'}
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow =} \KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\NormalTok{female_people =}\StringTok{ }\NormalTok{titanic_data[titanic_data}\OperatorTok{$}\NormalTok{Sex }\OperatorTok{==}\StringTok{ "male"}\NormalTok{,]}
\NormalTok{male_people =}\StringTok{ }\NormalTok{titanic_data[titanic_data}\OperatorTok{$}\NormalTok{Sex }\OperatorTok{==}\StringTok{ "female"}\NormalTok{,]}
\KeywordTok{boxplot}\NormalTok{(female_people}\OperatorTok{$}\NormalTok{Age}\OperatorTok{~}\NormalTok{female_people}\OperatorTok{$}\NormalTok{Pclass, }\DataTypeTok{main =} \StringTok{"Pclass by age (female)"}\NormalTok{,}
        \DataTypeTok{xlab =} \StringTok{"Pclass"}\NormalTok{, }\DataTypeTok{ylab =} \StringTok{"Age"}\NormalTok{)}
\KeywordTok{boxplot}\NormalTok{(male_people}\OperatorTok{$}\NormalTok{Age}\OperatorTok{~}\NormalTok{male_people}\OperatorTok{$}\NormalTok{Pclass, }\DataTypeTok{main =} \StringTok{"Pclass by age (male)"}\NormalTok{,}
        \DataTypeTok{xlab =} \StringTok{"Pclass"}\NormalTok{, }\DataTypeTok{ylab =} \StringTok{"Age"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{titanic-cleaning_files/figure-latex/unnamed-chunk-10-1.pdf}

Per tractar els valors perduts tindrem en compte la informació observada
a la gràfica anterior. Per realitzar aquesta tasca s'ha creat una funció
\texttt{AgeMean} per obtenir la mitjana d'edats de les dones i dels
homes segons la classe, i després s'ha creat una altra funció assignar
als passatgers que tenen l'edat en blanc la mitjana corresponent al seu
gènere i a la classe en la que viatjava.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{AgeMean <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(age) \{}
  \KeywordTok{round}\NormalTok{(}\KeywordTok{summary}\NormalTok{(age)[}\StringTok{'Mean'}\NormalTok{])}
\NormalTok{\}}

\NormalTok{female_mean_ages =}\StringTok{ }\KeywordTok{tapply}\NormalTok{(female_people}\OperatorTok{$}\NormalTok{Age, female_people}\OperatorTok{$}\NormalTok{Pclass, AgeMean)}
\NormalTok{male_mean_ages =}\StringTok{ }\KeywordTok{tapply}\NormalTok{(male_people}\OperatorTok{$}\NormalTok{Age, male_people}\OperatorTok{$}\NormalTok{Pclass, AgeMean)}

\NormalTok{AgeImpute <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(row) \{}
\NormalTok{  sex <-}\StringTok{ }\NormalTok{row[}\StringTok{'Sex'}\NormalTok{]}
\NormalTok{  age <-}\StringTok{ }\NormalTok{row[}\StringTok{'Age'}\NormalTok{]}
\NormalTok{  pclass <-}\StringTok{ }\NormalTok{row[}\StringTok{'Pclass'}\NormalTok{]}
\NormalTok{  value <-}\StringTok{ }\NormalTok{age}
  \ControlFlowTok{if}\NormalTok{ (}\KeywordTok{is.na}\NormalTok{(age)) \{}
    \ControlFlowTok{if}\NormalTok{ (sex }\OperatorTok{==}\StringTok{ "female"}\NormalTok{) \{}
\NormalTok{      value <-}\StringTok{ }\NormalTok{female_mean_ages[pclass]}
\NormalTok{    \} }\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{      value <-}\StringTok{ }\NormalTok{male_mean_ages[pclass]}
\NormalTok{    \}}
\NormalTok{  \}}
  \KeywordTok{return}\NormalTok{(}\KeywordTok{as.numeric}\NormalTok{(value))}
\NormalTok{\}}

\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{Age <-}\StringTok{ }\KeywordTok{apply}\NormalTok{(titanic_data[, }\KeywordTok{c}\NormalTok{(}\StringTok{"Sex"}\NormalTok{, }\StringTok{"Age"}\NormalTok{, }\StringTok{"Pclass"}\NormalTok{)], }\DecValTok{1}\NormalTok{, AgeImpute)}
\end{Highlighting}
\end{Shaded}

\hypertarget{identificaciuxf3-de-valors-extrems}{%
\subsection{Identificació de valors
extrems}\label{identificaciuxf3-de-valors-extrems}}

Els valors extrems o outliers són registres que destacant per ser molt
distants al valor central del conjunt. Generalment es considera un
outlier quan el seu valor es troba allunyat 3 desviacions estàndars
respecte la mitjana, un instrument gràfic que ens permet visualitzar
ràpidament aquests valors són els diagrames de caixes. Una altre forma
de detectar-los a R, es mitjançant la funció boxplot.stats()

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fare.bp<-}\KeywordTok{boxplot}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Fare, }\DataTypeTok{main=}\StringTok{"Fare"}\NormalTok{, }\DataTypeTok{col=}\StringTok{"darkgreen"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{titanic-cleaning_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot.stats}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Fare)}\OperatorTok{$}\NormalTok{out}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   [1]  71.2833 263.0000 146.5208  82.1708  76.7292  80.0000  83.4750  73.5000
##   [9] 263.0000  77.2875 247.5208  73.5000  77.2875  79.2000  66.6000  69.5500
##  [17]  69.5500 146.5208  69.5500 113.2750  76.2917  90.0000  83.4750  90.0000
##  [25]  79.2000  86.5000 512.3292  79.6500 153.4625 135.6333  77.9583  78.8500
##  [33]  91.0792 151.5500 247.5208 151.5500 110.8833 108.9000  83.1583 262.3750
##  [41] 164.8667 134.5000  69.5500 135.6333 153.4625 133.6500  66.6000 134.5000
##  [49] 263.0000  75.2500  69.3000 135.6333  82.1708 211.5000 227.5250  73.5000
##  [57] 120.0000 113.2750  90.0000 120.0000 263.0000  81.8583  89.1042  91.0792
##  [65]  90.0000  78.2667 151.5500  86.5000 108.9000  93.5000 221.7792 106.4250
##  [73]  71.0000 106.4250 110.8833 227.5250  79.6500 110.8833  79.6500  79.2000
##  [81]  78.2667 153.4625  77.9583  69.3000  76.7292  73.5000 113.2750 133.6500
##  [89]  73.5000 512.3292  76.7292 211.3375 110.8833 227.5250 151.5500 227.5250
##  [97] 211.3375 512.3292  78.8500 262.3750  71.0000  86.5000 120.0000  77.9583
## [105] 211.3375  79.2000  69.5500 120.0000  93.5000  80.0000  83.1583  69.5500
## [113]  89.1042 164.8667  69.5500  83.1583  82.2667 262.3750  76.2917 263.0000
## [121] 262.3750 262.3750 263.0000 211.5000 211.5000 221.7792  78.8500 221.7792
## [129]  75.2417 151.5500 262.3750  83.1583 221.7792  83.1583  83.1583 247.5208
## [137]  69.5500 134.5000 227.5250  73.5000 164.8667 211.5000  71.2833  75.2500
## [145] 106.4250 134.5000 136.7792  75.2417 136.7792  82.2667  81.8583 151.5500
## [153]  93.5000 135.6333 146.5208 211.3375  79.2000  69.5500 512.3292  73.5000
## [161]  69.5500  69.5500 134.5000  81.8583 262.3750  93.5000  79.2000 164.8667
## [169] 211.5000  90.0000 108.9000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Age.bp<-}\KeywordTok{boxplot}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Age, }\DataTypeTok{main=}\StringTok{"Age"}\NormalTok{, }\DataTypeTok{col=}\StringTok{"darkgreen"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{titanic-cleaning_files/figure-latex/unnamed-chunk-12-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot.stats}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Age)}\OperatorTok{$}\NormalTok{out}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 66.0 65.0 71.0 70.5 61.0 62.0 63.0 65.0 61.0 60.0 64.0 65.0 63.0 71.0 64.0
## [16] 62.0 62.0 60.0 61.0 80.0 70.0 60.0 60.0 70.0 62.0 74.0 62.0 63.0 60.0 60.0
## [31] 67.0 76.0 63.0 61.0 60.5 64.0 61.0 60.0 64.0 64.0
\end{verbatim}

Si ens fixem en els valors extrems resultants, en el cas d'Age, són
valors que poden donar-se perfectament, ja que podem tenir persones de
80 anys com a passatgers. En el cas de Fare, són valors que també es
poden haver donat, ja que el preu que hagi pugut pagar cada passatger
pot tenir una gran oscil.lació, i es poden donar valors de 0 a 500
perfectament. Es per això, que tot i haver-los detectat, hem decidit no
tractar-los de manera diferent a com han estat recollits.

\hypertarget{anuxe0lisi-de-les-dades}{%
\section{Anàlisi de les dades}\label{anuxe0lisi-de-les-dades}}

\hypertarget{comprovaciuxf3-de-la-normalitat-i-homogeneuxeftat-de-la-variuxe0ncia}{%
\subsection{Comprovació de la normalitat i homogeneïtat de la
variància}\label{comprovaciuxf3-de-la-normalitat-i-homogeneuxeftat-de-la-variuxe0ncia}}

Per comprobar si les variables Age i Fare segueixen una distribució
normal, podem tenir una aproximació amb la funció qqnorm, la qual
comparara els quartils de la distribució observada amb els quartils
teòrics d'una distribució normal, com més s'aproximen a les dades d'una
normal, més alineats es trobaran els punts al voltant de la recta.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Representació de la distribució de la variable Fare mitjançant un histograma: }
\KeywordTok{hist}\NormalTok{(}\DataTypeTok{x=}\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{Fare, }\DataTypeTok{main=}\StringTok{"Histograma Fare"}\NormalTok{, }\DataTypeTok{xlab=}\StringTok{"Fare"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"Frecuencia"}\NormalTok{, }\DataTypeTok{col =} \StringTok{"darkgreen"}\NormalTok{, }\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1200}\NormalTok{), }\DataTypeTok{xlim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{600}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{titanic-cleaning_files/figure-latex/unnamed-chunk-13-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qqnorm}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Fare) }
\KeywordTok{qqline}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Fare, }\DataTypeTok{col=}\StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{titanic-cleaning_files/figure-latex/unnamed-chunk-13-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(titanic_data,}\KeywordTok{aes}\NormalTok{(Fare)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{size=}\DecValTok{1}\NormalTok{, }\DataTypeTok{alpha=} \FloatTok{0.6}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{ylab}\NormalTok{(}\StringTok{"DENSITAT"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{titanic-cleaning_files/figure-latex/unnamed-chunk-13-3.pdf}
Mitjançant els gràfics anteriors, podem veure que hi ha força desviaciço
en alguns trams, i per tant, possibles evidències de que no segueix una
distribució normal. Ho contrasterem mitjançant el Test Lilliefors
(asumeix mediana i variança poblacionals desconegudes) \emph{Hipòtesis
nul.la: les dades procedeixen d'una distribució normal }Hipòtesis
alterantiva: no procedeixen d'una distribució normal.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#TEST Lilliefors}
\KeywordTok{lillie.test}\NormalTok{(}\DataTypeTok{x=}\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{Fare)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  titanic_data$Fare
## D = 0.2858, p-value < 2.2e-16
\end{verbatim}

Rebutjem la hipòtesis nul.la, la diferència és estadísticament
significativa, és a dir, amb un 95\% de confiança podem dir que la
variable Fare no segueix una distribució normal. Si repetim el mateix
procediment per la variable Age:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Representació de la distribució de la variable Fare mitjançant un histograma: }
\KeywordTok{hist}\NormalTok{(}\DataTypeTok{x=}\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{Age, }\DataTypeTok{main=}\StringTok{"Histograma Age"}\NormalTok{, }\DataTypeTok{xlab=}\StringTok{"Age"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"Frecuencia"}\NormalTok{, }\DataTypeTok{col =} \StringTok{"darksalmon"}\NormalTok{, }\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{350}\NormalTok{), }\DataTypeTok{xlim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{100}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{titanic-cleaning_files/figure-latex/unnamed-chunk-15-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qqnorm}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Age) }
\KeywordTok{qqline}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Age, }\DataTypeTok{col=}\StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{titanic-cleaning_files/figure-latex/unnamed-chunk-15-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(titanic_data,}\KeywordTok{aes}\NormalTok{(Age)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{size=}\DecValTok{1}\NormalTok{, }\DataTypeTok{alpha=} \FloatTok{0.6}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{ylab}\NormalTok{(}\StringTok{"DENSITAT"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{titanic-cleaning_files/figure-latex/unnamed-chunk-15-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{lillie.test}\NormalTok{(}\DataTypeTok{x=}\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{Age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  titanic_data$Age
## D = 0.11525, p-value < 2.2e-16
\end{verbatim}

Podem veure novament, com la variable edat per un nivell de confiança
del 95\% rebutjem la hipòtesis nul.la, i per tant, no podem acceptar que
la variable segueixi una distribució normal.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pairs}\NormalTok{(titanic_data[, }\KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{7}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\includegraphics{titanic-cleaning_files/figure-latex/unnamed-chunk-16-1.pdf}

\#Comprovació de la HOMOGENEITAT DE LA VARIANCIA Finalment comprovarem
l'homoscedasticitat de les dades, és a dir, la igualtat de variàncies
per Fare i Age. Ja que no tenim seguretat que provinguin d'una població
normal, hem utilitzat el test de Levene amb la mediana com a mesura de
centralitat, juntament amb el test no paramètric Fligner-Killeen que
també es basa en la mediana. \emph{Hipòtesis nul.la: la variança és
constant. }Hipòtesis alterantiva: la variança no és constant.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{aggregate}\NormalTok{(Fare}\OperatorTok{~}\NormalTok{Survived, }\DataTypeTok{data =}\NormalTok{ titanic_data, }\DataTypeTok{FUN =}\NormalTok{ var)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Survived     Fare
## 1        0 1217.107
## 2        1 4705.192
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{aggregate}\NormalTok{(Age}\OperatorTok{~}\NormalTok{Survived, }\DataTypeTok{data =}\NormalTok{ titanic_data, }\DataTypeTok{FUN =}\NormalTok{ var)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Survived      Age
## 1        0 161.2441
## 2        1 198.1852
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Levene }\AlertTok{TEST}
\NormalTok{levene <-}\StringTok{ }\KeywordTok{filter}\NormalTok{(}\DataTypeTok{.data =}\NormalTok{ titanic_data, Survived }\OperatorTok{%in%}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"0"}\NormalTok{, }\StringTok{"1"}\NormalTok{))}
\KeywordTok{leveneTest}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ levene}\OperatorTok{$}\NormalTok{Fare, }\DataTypeTok{group =}\NormalTok{ levene}\OperatorTok{$}\NormalTok{Survived, }\DataTypeTok{center =} \StringTok{"median"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Levene's Test for Homogeneity of Variance (center = "median")
##         Df F value    Pr(>F)    
## group    1  56.493 1.043e-13 ***
##       1307                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{leveneTest}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ levene}\OperatorTok{$}\NormalTok{Age, }\DataTypeTok{group =}\NormalTok{ levene}\OperatorTok{$}\NormalTok{Survived, }\DataTypeTok{center =} \StringTok{"median"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Levene's Test for Homogeneity of Variance (center = "median")
##         Df F value  Pr(>F)  
## group    1  5.1627 0.02324 *
##       1307                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Test Fligner-Killeen}
\KeywordTok{fligner.test}\NormalTok{(Fare }\OperatorTok{~}\StringTok{ }\NormalTok{Survived, }\DataTypeTok{data=}\NormalTok{titanic_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Fligner-Killeen test of homogeneity of variances
## 
## data:  Fare by Survived
## Fligner-Killeen:med chi-squared = 128.39, df = 1, p-value < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{fligner.test}\NormalTok{(Age }\OperatorTok{~}\StringTok{ }\NormalTok{Survived, }\DataTypeTok{data=}\NormalTok{titanic_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Fligner-Killeen test of homogeneity of variances
## 
## data:  Age by Survived
## Fligner-Killeen:med chi-squared = 4.8298, df = 1, p-value = 0.02797
\end{verbatim}

En els dos tests realitzats, podem veure com tan la variable Fare com
Age, es rebutja la hipòtesis nula, és a dir, amb un nivell de confiança
del 95\%, podem concloure que en ambdos grups la variança no és
constant.

\hypertarget{aplicaciuxf3-de-proves-estaduxedstiques}{%
\subsection{Aplicació de proves
estadístiques}\label{aplicaciuxf3-de-proves-estaduxedstiques}}

\hypertarget{contrast-dhipuxf2tesis}{%
\subsubsection{Contrast d'hipòtesis}\label{contrast-dhipuxf2tesis}}

Ens interessa descriure la relació entre la supervivència i les
variables edat, classe i gènere. Per a això, en primer lloc hem dut a
terme un gràfic mitjançant diagrames de barres amb la quantitat de morts
i supervivents segons la classe en la que viatjaven, l'edat o el gènere.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plotbyClass<-}\KeywordTok{ggplot}\NormalTok{(titanic_data,}\KeywordTok{aes}\NormalTok{(Pclass,}\DataTypeTok{fill=}\NormalTok{Survived))}\OperatorTok{+}\KeywordTok{geom_bar}\NormalTok{() }\OperatorTok{+}\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{"Class"}\NormalTok{, }\DataTypeTok{y=}\StringTok{"Passengers"}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{guides}\NormalTok{(}\DataTypeTok{fill=}\KeywordTok{guide_legend}\NormalTok{(}\DataTypeTok{title=}\StringTok{""}\NormalTok{))}\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\KeywordTok{c}\NormalTok{(}\StringTok{"darksalmon"}\NormalTok{,}\StringTok{"darkseagreen4"}\NormalTok{))}\OperatorTok{+}\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Survived by Class"}\NormalTok{)}
\NormalTok{plotbyAge<-}\KeywordTok{ggplot}\NormalTok{(titanic_data,}\KeywordTok{aes}\NormalTok{(Age,}\DataTypeTok{fill=}\NormalTok{Survived))}\OperatorTok{+}\KeywordTok{geom_bar}\NormalTok{() }\OperatorTok{+}\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{"Age"}\NormalTok{, }\DataTypeTok{y=}\StringTok{"Passengers"}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{guides}\NormalTok{(}\DataTypeTok{fill=}\KeywordTok{guide_legend}\NormalTok{(}\DataTypeTok{title=}\StringTok{""}\NormalTok{))}\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\KeywordTok{c}\NormalTok{(}\StringTok{"darksalmon"}\NormalTok{,}\StringTok{"darkseagreen4"}\NormalTok{))}\OperatorTok{+}\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Survived by Age"}\NormalTok{)}
\NormalTok{plotbySex<-}\KeywordTok{ggplot}\NormalTok{(titanic_data,}\KeywordTok{aes}\NormalTok{(Sex,}\DataTypeTok{fill=}\NormalTok{Survived))}\OperatorTok{+}\KeywordTok{geom_bar}\NormalTok{() }\OperatorTok{+}\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{"Sex"}\NormalTok{, }\DataTypeTok{y=}\StringTok{"Passengers"}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{guides}\NormalTok{(}\DataTypeTok{fill=}\KeywordTok{guide_legend}\NormalTok{(}\DataTypeTok{title=}\StringTok{""}\NormalTok{))}\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\KeywordTok{c}\NormalTok{(}\StringTok{"darksalmon"}\NormalTok{,}\StringTok{"darkseagreen4"}\NormalTok{))}\OperatorTok{+}\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Survived by Sex"}\NormalTok{)}
\KeywordTok{grid.arrange}\NormalTok{(plotbyClass,plotbyAge,plotbySex,}\DataTypeTok{ncol=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{titanic-cleaning_files/figure-latex/unnamed-chunk-18-1.pdf}
CRITERIS D'ÈXIT: 1. Van sobreviure més del 50\% dels passatgers?
Existeix diferència significativa per un nivell de significació del 5\%?
Per poder contrastar la hipòtesis, utilitzarem el test binominal exacte.
H0: la proporció és major del 50\%. H1: la proporció no és major.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tableSurvived<-}\KeywordTok{table}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Survived)}
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Survived))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##         0         1 
## 0.6226127 0.3773873
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{binom.test}\NormalTok{(}\DataTypeTok{x =} \KeywordTok{c}\NormalTok{(}\DecValTok{494}\NormalTok{, }\DecValTok{815}\NormalTok{), }\DataTypeTok{alternative =} \StringTok{"less"}\NormalTok{, }\DataTypeTok{conf.level =} \FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Exact binomial test
## 
## data:  c(494, 815)
## number of successes = 494, number of trials = 1309, p-value < 2.2e-16
## alternative hypothesis: true probability of success is less than 0.5
## 95 percent confidence interval:
##  0.0000000 0.3999954
## sample estimates:
## probability of success 
##              0.3773873
\end{verbatim}

Amb un nivell de confiança del 95\% podem concloure que no va sobreviure
més del 50\% dels passatgers.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Hi ha diferència significativa entre la proporció d'homes i dones que
  van sobreviure? H0: les dues variables són independents. H1: les dues
  variables no són independents. Per esbrinar si hi ha diferència, hem
  executat el test de fisher, el qual ens permet estudiar si existeix
  asociació entre dues variables qualitatives.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{table_Sex<-}\KeywordTok{table}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Sex, titanic_data}\OperatorTok{$}\NormalTok{Survived)}
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Sex, titanic_data}\OperatorTok{$}\NormalTok{Survived), }\DataTypeTok{margin=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         
##                  0         1
##   female 0.1738197 0.8261803
##   male   0.8706999 0.1293001
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{fisher.test}\NormalTok{(table_Sex, }\DataTypeTok{alternative =} \StringTok{"two.sided"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Fisher's Exact Test for Count Data
## 
## data:  table_Sex
## p-value < 2.2e-16
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##  0.02255471 0.04318701
## sample estimates:
## odds ratio 
## 0.03139796
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Si fem el test X^2 també és significatiu.}
\KeywordTok{chisq.test}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ table_Sex)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's Chi-squared test with Yates' continuity correction
## 
## data:  table_Sex
## X-squared = 617.31, df = 1, p-value < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{chisq.test}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ table_Sex)}\OperatorTok{$}\NormalTok{residuals}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         
##                   0          1
##   female -12.278067  15.770495
##   male     9.128705 -11.725314
\end{verbatim}

Amb un 95\% de confiança podem rebutjar el test, i per tant, afirmar que
les dues variables estàn relacionades. Concretament, s'esperava un
11.7\% més d'homes que sobrevisques i un -15.8\% de dones.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Hi ha diferències en la supervivencia segons la classe en la que
  viatjaven? H0: les dues variables són independents. H1: les dues
  variables no són independents.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{table_Class<-}\KeywordTok{table}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Pclass, titanic_data}\OperatorTok{$}\NormalTok{Survived)}
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{Pclass, titanic_data}\OperatorTok{$}\NormalTok{Survived), }\DataTypeTok{margin=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    
##             0         1
##   1 0.4241486 0.5758514
##   2 0.5776173 0.4223827
##   3 0.7306065 0.2693935
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{fisher.test}\NormalTok{(table_Class, }\DataTypeTok{alternative =} \StringTok{"two.sided"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Fisher's Exact Test for Count Data
## 
## data:  table_Class
## p-value < 2.2e-16
## alternative hypothesis: two.sided
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Si fem el test X^2 també és significatiu.}
\KeywordTok{chisq.test}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ table_Class)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's Chi-squared test
## 
## data:  table_Class
## X-squared = 91.724, df = 2, p-value < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{chisq.test}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ table_Class)}\OperatorTok{$}\NormalTok{residuals}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    
##              0          1
##   1 -4.5203721  5.8061669
##   2 -0.9490707  1.2190286
##   3  3.6442905 -4.6808887
\end{verbatim}

Podem afirmar novament amb un 95\% de confiança que hi ha relació entre
ambdues variables, on s'esperava un 4.7\% més de supervivents de la
classe 3, en canvi de la classe 1 s'esperava un 5.8\% menys.

A continuació discretitzarem la variable edat. El nombre d'intervals
escollits=3, utilitzarem el mètode d'igual freqüència per tal de
mantenir sempre la mateixa freqüència.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dis1<-}\KeywordTok{table}\NormalTok{(}\KeywordTok{discretize}\NormalTok{(}\DataTypeTok{x=}\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{Age, }\DataTypeTok{method =} \StringTok{"frequency"}\NormalTok{, }\DataTypeTok{breaks =}\DecValTok{4}\NormalTok{, }\DataTypeTok{include.lowest =} \OtherTok{TRUE}\NormalTok{))}
\NormalTok{dis1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## [0.17,22)   [22,26)   [26,37)   [37,80] 
##       290       297       394       328
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{AgeD[titanic_data}\OperatorTok{$}\NormalTok{Age }\OperatorTok{<}\DecValTok{21}\NormalTok{] <-}\StringTok{ "Menors de 21 anys"}
\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{AgeD[titanic_data}\OperatorTok{$}\NormalTok{Age }\OperatorTok{>=}\StringTok{ }\DecValTok{21} \OperatorTok{&}\StringTok{ }\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{Age }\OperatorTok{<}\StringTok{ }\DecValTok{28}\NormalTok{] <-}\StringTok{ "Entre 21 i 28 anys"}
\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{AgeD[titanic_data}\OperatorTok{$}\NormalTok{Age }\OperatorTok{>=}\StringTok{ }\DecValTok{28} \OperatorTok{&}\StringTok{ }\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{Age }\OperatorTok{<}\StringTok{ }\DecValTok{39}\NormalTok{] <-}\StringTok{ "Entre 28 i 39 anys"}
\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{AgeD[titanic_data}\OperatorTok{$}\NormalTok{Age}\OperatorTok{>=}\StringTok{ }\DecValTok{39}\NormalTok{] <-}\StringTok{ "Majors de 39"}
\end{Highlighting}
\end{Shaded}

Tot seguit fem de la nova variable un factor

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{AgeD <-}
\StringTok{  }\KeywordTok{factor}\NormalTok{(}
\NormalTok{    titanic_data}\OperatorTok{$}\NormalTok{AgeD,}
    \DataTypeTok{ordered =} \OtherTok{FALSE}\NormalTok{,}
    \DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}
      \StringTok{"Menors de 21 anys"}\NormalTok{,}
      \StringTok{"Entre 21 i 28 anys"}\NormalTok{,}
      \StringTok{"Entre 28 i 39 anys"}\NormalTok{,}
      \StringTok{"Majors de 39"}
\NormalTok{    )}
\NormalTok{  )}
\KeywordTok{summary}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{AgeD)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Menors de 21 anys Entre 21 i 28 anys Entre 28 i 39 anys       Majors de 39 
##                249                476                308                276
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Hi ha diferències en la supervivència segons l'edat? H0: les dues
  variables són independents. H1: les dues variables no són
  independents.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{table_AgeD<-}\KeywordTok{table}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{AgeD, titanic_data}\OperatorTok{$}\NormalTok{Survived)}
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{AgeD, titanic_data}\OperatorTok{$}\NormalTok{Survived), }\DataTypeTok{margin=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                     
##                              0         1
##   Menors de 21 anys  0.5421687 0.4578313
##   Entre 21 i 28 anys 0.6869748 0.3130252
##   Entre 28 i 39 anys 0.6038961 0.3961039
##   Majors de 39       0.6050725 0.3949275
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{fisher.test}\NormalTok{(table_AgeD, }\DataTypeTok{alternative =} \StringTok{"two.sided"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Fisher's Exact Test for Count Data
## 
## data:  table_AgeD
## p-value = 0.001054
## alternative hypothesis: two.sided
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Si fem el test X^2 també és significatiu.}
\KeywordTok{chisq.test}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ table_AgeD)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's Chi-squared test
## 
## data:  table_AgeD
## X-squared = 16.07, df = 3, p-value = 0.001097
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{chisq.test}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ table_AgeD)}\OperatorTok{$}\NormalTok{residuals}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                     
##                               0          1
##   Menors de 21 anys  -1.6087345  2.0663302
##   Entre 21 i 28 anys  1.7796097 -2.2858098
##   Entre 28 i 39 anys -0.4162870  0.5346975
##   Majors de 39       -0.3693010  0.4743467
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{chisq.test}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ table_AgeD)}\OperatorTok{$}\NormalTok{stdres}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                     
##                               0          1
##   Menors de 21 anys  -2.9100981  2.9100981
##   Entre 21 i 28 anys  3.6314363 -3.6314363
##   Entre 28 i 39 anys -0.7749112  0.7749112
##   Majors de 39       -0.6767162  0.6767162
\end{verbatim}

Podem afirmar novament amb un 95\% de confiança que hi ha relació entre
ambdues variables.S'esperava un 2,3\% més de supervivents en la franja
d'edat 21-28 anys, en canvi, s'esperava un 2\% menys en la de menors de
21.

Finalment, ens interessava conèixer si la probabilitat de sobreviure
tenia alguna relació amb el tamany de la família? En primer lloc, el que
hem fet es crear una nova variable, anomenada FamilySize, que és la suma
de SibSp i Parch. On a més a més, hem analitzat, si tenía valors
extrems, seguia una distribució normal i si la variança era constant
entre els diferents grups.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Creació nova variable: }
\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{FamilySize <-}\StringTok{ }\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{SibSp }\OperatorTok{+}\StringTok{ }\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{Parch }\OperatorTok{+}\DecValTok{1}\NormalTok{;}
\KeywordTok{hist}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{FamilySize)}
\end{Highlighting}
\end{Shaded}

\includegraphics{titanic-cleaning_files/figure-latex/unnamed-chunk-25-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot.stats}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{FamilySize)}\OperatorTok{$}\NormalTok{out}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   [1]  5  7  6  5  7  6  4  6  4  8  6  7  8  4  5  6  4  7  5 11  6  6  6  5 11
##  [26]  7  4 11  5  7  7  6  6  4  4  5 11  6  6  5  8  4  5  4  5  6  6  4  4  4
##  [51]  4  8  5  4  4  7  7  5  4  4  7  4  4  6  6  6  4  8  8  4  6  4  5  5  4
##  [76]  4  5  4  6  4 11  4  7  6  6 11  7  4 11  6  4  5  4  4  4  6  6  5  6  4
## [101]  5  8  8  5  4  7  5  7  4 11  7  4  4  4  4  4 11  4  4 11 11  7  4  5  5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{fligner.test}\NormalTok{(Age }\OperatorTok{~}\StringTok{ }\NormalTok{Survived, }\DataTypeTok{data=}\NormalTok{titanic_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Fligner-Killeen test of homogeneity of variances
## 
## data:  Age by Survived
## Fligner-Killeen:med chi-squared = 4.8298, df = 1, p-value = 0.02797
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{lillie.test}\NormalTok{(}\DataTypeTok{x=}\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{FamilySize)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  titanic_data$FamilySize
## D = 0.31514, p-value < 2.2e-16
\end{verbatim}

Podem veure, que les famílies més grans comptant, pares, fills, germans
i parelles és de 11, número que hem donat per vàlid. Mitjançant els
diferents test, veiem però que no segueix una distribució normal, com
tampoc presenta una variança constant. El que farem a continuació serà
discretitzar la variable en 3 grups:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{FamilySize)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   1.000   1.000   1.884   2.000  11.000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Farem serà discretitzar també la variable Família Size. }
\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{FamilySizeD[titanic_data}\OperatorTok{$}\NormalTok{FamilySize }\OperatorTok{<}\DecValTok{2}\NormalTok{] <-}\StringTok{ "Adult sol"}
\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{FamilySizeD[titanic_data}\OperatorTok{$}\NormalTok{FamilySize }\OperatorTok{>=}\StringTok{ }\DecValTok{2} \OperatorTok{&}\StringTok{ }\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{FamilySize }\OperatorTok{<}\StringTok{ }\DecValTok{5}\NormalTok{] <-}\StringTok{ "Famílies de dos a 4 membres"}
\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{FamilySizeD[titanic_data}\OperatorTok{$}\NormalTok{FamilySize}\OperatorTok{>=}\DecValTok{5}\NormalTok{] <-}\StringTok{ "Famílies amb més de 4 membres"}
\end{Highlighting}
\end{Shaded}

Tot seguit fem de la nova variable un factor

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{titanic_data}\OperatorTok{$}\NormalTok{FamilySizeD<-}
\StringTok{  }\KeywordTok{factor}\NormalTok{(}
\NormalTok{    titanic_data}\OperatorTok{$}\NormalTok{FamilySizeD,}
    \DataTypeTok{ordered =} \OtherTok{FALSE}\NormalTok{,}
    \DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}
      \StringTok{"Adult sol"}\NormalTok{,}
      \StringTok{"Famílies de dos a 4 membres"}\NormalTok{,}
      \StringTok{"Famílies amb més de 4 membres"}
\NormalTok{    )}
\NormalTok{  )}

\KeywordTok{summary}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{FamilySizeD)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                     Adult sol   Famílies de dos a 4 membres 
##                           790                           437 
## Famílies amb més de 4 membres 
##                            82
\end{verbatim}

\emph{H0:Les variables són independents, és a dir, el fet de sobreviure
no varia segons el tamany de la unitat familiar. }H1: Les variables són
dependents.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{table_Family<-}\KeywordTok{table}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{FamilySizeD, titanic_data}\OperatorTok{$}\NormalTok{Survived)}
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(titanic_data}\OperatorTok{$}\NormalTok{FamilySizeD, titanic_data}\OperatorTok{$}\NormalTok{Survived), }\DataTypeTok{margin=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                
##                                         0         1
##   Adult sol                     0.7075949 0.2924051
##   Famílies de dos a 4 membres   0.4393593 0.5606407
##   Famílies amb més de 4 membres 0.7804878 0.2195122
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{fisher.test}\NormalTok{(table_Family, }\DataTypeTok{alternative =} \StringTok{"two.sided"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Fisher's Exact Test for Count Data
## 
## data:  table_Family
## p-value < 2.2e-16
## alternative hypothesis: two.sided
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Si fem el test X^2 també és significatiu.}
\KeywordTok{chisq.test}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ table_Family)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's Chi-squared test
## 
## data:  table_Family
## X-squared = 95.437, df = 2, p-value < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{chisq.test}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ table_Family)}\OperatorTok{$}\NormalTok{residuals}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                
##                                         0         1
##   Adult sol                      3.027142 -3.888196
##   Famílies de dos a 4 membres   -4.854939  6.235900
##   Famílies amb més de 4 membres  1.811806 -2.327164
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{chisq.test}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ table_Family)}\OperatorTok{$}\NormalTok{stdres}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                
##                                         0         1
##   Adult sol                      7.825738 -7.825738
##   Famílies de dos a 4 membres   -9.682817  9.682817
##   Famílies amb més de 4 membres  3.046250 -3.046250
\end{verbatim}

Podem veure amb un nivell de significació del 5\%, com el tamany de la
unita familiar també va influir, van sobreviure un 9.7\% més de famílies
de 2-4 membres del que s'esperava, per contra, s'esperava que un 7.8\%
més d'adults sols sobrevisques.

Mitjançant els gràfics de barres, les taules de contingencia i els tests
realitzats podem concloure: \textbf{La proporció d'homes i dones que van
sobreviure és força diferent, homes: 109, dones: 385, si ens fixem en el
\% respecte el seu gènere, en les dones és del 83\% mentre que pels
homes és del 23\%. }Referent a la classe en la que viatjaven, si ens
fixem en el gràfic, el nombre de personas que més van sobreviure són els
que viatjaven en 3 classe, cal dir, però, que el nombre de passatgers
d'aquesta classe és molt major. Si ens fixem en el \% dins de cada
classe, són els de primera classe els que tenen una ràtio més alta de
supervivència. \textbf{Cal destacar també que la proporció d'adults sols
és més del 50\%, i que la franja on hi trobem més viatjants és la franja
d'edat entre 21 i 28 anys. }Després de realitzar els 4 test, podem veure
que les diferències són significatives, i que tan l'edat, la classe en
la que viatjaven, el gènere com el tamany de la unitat familiar van ser
significatius per la superviència.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow=}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\KeywordTok{plot}\NormalTok{(table_Class, }\DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"darksalmon"}\NormalTok{,}\StringTok{"darkseagreen4"}\NormalTok{), }\DataTypeTok{main =} \StringTok{"Survived vs. Class"}\NormalTok{)}
\KeywordTok{plot}\NormalTok{(table_Sex, }\DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"darksalmon"}\NormalTok{,}\StringTok{"darkseagreen4"}\NormalTok{), }\DataTypeTok{main =} \StringTok{"Survived vs. Sex"}\NormalTok{)}
\KeywordTok{plot}\NormalTok{(table_AgeD, }\DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"darksalmon"}\NormalTok{,}\StringTok{"darkseagreen4"}\NormalTok{), }\DataTypeTok{main =} \StringTok{"Survived vs. Age"}\NormalTok{)}
\KeywordTok{plot}\NormalTok{(table_Family, }\DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"darksalmon"}\NormalTok{,}\StringTok{"darkseagreen4"}\NormalTok{), }\DataTypeTok{main =} \StringTok{"Survived vs. Family Size"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{titanic-cleaning_files/figure-latex/unnamed-chunk-29-1.pdf}

\hypertarget{matriu-de-correlaciuxf3}{%
\subsubsection{Matriu de correlació}\label{matriu-de-correlaciuxf3}}

\hypertarget{regressiuxf3-loguxedstica}{%
\subsubsection{Regressió logística}\label{regressiuxf3-loguxedstica}}

\hypertarget{representaciuxf3-dels-resultats}{%
\section{Representació dels
resultats}\label{representaciuxf3-dels-resultats}}

\hypertarget{resoluciuxf3-del-problema}{%
\section{Resolució del problema}\label{resoluciuxf3-del-problema}}


\end{document}
